version: '{build}-{branch}'
image: Visual Studio 2015

services:
- mssql2008r2sp2

build_script:
- pwsh: dotnet build -c Release

test_script:
- pwsh: dotnet test ./test/MicroOrm.Dapper.Repositories.Tests -c Release --no-build
